### ISSUE TITLE
The Elder Scroll II: Daggerfall - DaggerXL

### ISSUE THREAD

**Issue by wonea** [piranha/osgameclones#113]
DaggerXL
http://xlengine.com/blog/

The old blog
https://daggerxl.wordpress.com/

**Comment by wonea** [comment]
Not a playable game yet, waiting for more from this project

**Comment by scrawl** [comment]
Last I checked it's not open source, but he has plans to release the source eventually.

**Comment by wonea** [comment]
Thanks, will keep an eye on it. If you know about any other Elder Scrolls projects I'd be happy to know. Especially Redguard or Arena.

**Comment by wonea** [comment]
The source for the XL Engine has been released

http://xlengine.com/xl-engine-source-code/

https://github.com/luciusDXL/XL-Engine

Maybe put this under Daggerfall, although it does now support other games based on the same engine.
