### ISSUE TITLE
Multiple clones?

### ISSUE THREAD

**Issue by cxong** [piranha/osgameclones#124]
The latest version of [FreeBlocks](https://github.com/dorkster/freeblocks) clones two related games: Tetris Attack and Bejeweled. I think it's important to show that clones exist for particular games, but how should this be listed?

- List the game twice?
- Merge the two into "Match 3 games"?

Related: #123

**Comment by piranha** [comment]
I tend to like first more. So let's say first. :)

That's something I (and I would appreciate any input) need to think about - OSGC has grown a bit too fat and it becomes hard to navigate. It needs more interface, if I can say so, but I'm totally unsure where to go.
