### ISSUE TITLE
System Shock remake

### ISSUE THREAD

**Issue by wonea** [piranha/osgameclones#130]
Looks interesting but no code yet.

http://www.indiedb.com/games/citadel

http://freegamer.blogspot.co.uk/2014/09/citadel-makes-big-promises.html

**Comment by hhirsch** [comment]
Looks like closed source and just taking the original resources.

**Comment by wonea** [comment]
Now being open sourced

http://www.indiedb.com/games/citadel/news/citadel-now-being-developed-in-unity-5-and-open-source

https://github.com/JosiahJack/Citadel
