### ISSUE TITLE
Battletoads remake

### ISSUE THREAD

**Issue by wonea** [piranha/osgameclones#134]
https://en.wikipedia.org/wiki/Battletoads

Mentioned in comments, will be open sourced soon
https://www.youtube.com/watch?v=RxAwKKuzvkM *corrected 04/07/2015

**Comment by denilsonsa** [comment]
@wonea: I can't find the comment you mentioned. Try linking to the comment, instead of linking to the video. Also, the video is about the cartoon, which seems unrelated to osgameclones.

I'd suggest closing this issue unless there is a reference to the actual game anywhere.

**Comment by wonea** [comment]
I can't find the comment either, beg your pardon. Lets close this until I can confirm this with author of the remake
