### ISSUE TITLE
Halo remake

### ISSUE THREAD

**Issue by wonea** [piranha/osgameclones#135]
Found this

https://www.bungie.net/en/Forum/Post/113574775/0/0/1

Possible remake and source code.

https://i.imgur.com/OfTKTVr.jpg

**Comment by IBPX** [comment]
There's now an updated image, by the way.
![https://i.imgur.com/Jx4WaKG.jpg](https://i.imgur.com/Jx4WaKG.jpg)

**Comment by wonea** [comment]
Another update
![nycppva](https://cloud.githubusercontent.com/assets/557192/10124839/102d32f0-6558-11e5-8301-5b0c71f0abd1.png)

**Comment by piranha** [comment]
Looks sleek! :-)

**Comment by nikuda** [comment]
Closing because there's no trace of it after two years.
