### ISSUE TITLE
Try out this Populous clone

### ISSUE THREAD

**Issue by wonea** [piranha/osgameclones#143]
I found reference to someone trying to buld a Populous clone. Code needs checking over before we submit to osgameclones.

http://popms.net/forums/topic/491-populous-remake-attempt/

https://xp-dev.com/svn/cavernization/trunk/

**Comment by tukkek** [comment]
This sounds way too raw to enter the list for me. Are we going to add any code repository that doesn't have released download packages, no build instructions, website, etc? I'm literally unaware of what are the requirements to enter the list but I doubt this will be of use to anyone except programmers who are really desperate for a Populous clone codebase - in which case I doubt they need the OS clone list to find it or something similar.

**Comment by cxong** [comment]
I think it's fine; that's what the playable tag is for anyway.

**Comment by nikuda** [comment]
Closing since no update and what's there is too basic.
