### ISSUE TITLE
Transplant

### ISSUE THREAD

**Issue by piranha** [piranha/osgameclones#150]
a open source game that is inspired by a game called "Transplant" from the Commodore Amiga computer.
Please check it out: https://spaceshipduel.codeplex.com/

**Comment by wonea** [comment]
Will add but I'm fighting a couple of page deletions at the moment on Wikipedia. Wikipedians don't like short pages on obscure games :-(

**Comment by piranha** [comment]
Well, I guess we could live without pages on Wikipedia. :) Especially if you know a page describing the game, putting `[Name, "http://some/link"]` will point to that place.
