### ISSUE TITLE
Games out of order

### ISSUE THREAD

**Issue by wonea** [piranha/osgameclones#170]
Some games with double nodes; clones & reimplementations are out of order

![2015-05-10 16_11_52-open source game clones](https://cloud.githubusercontent.com/assets/557192/7554827/87d822de-f72f-11e4-8b80-c700cb335bbc.png)

**Comment by piranha** [comment]
That's interesting, I'm not really sure what happened there... Need to think for a bit.

**Comment by vloup** [comment]
I do plan to solve this but I have few questions regarding how I should proceed. I'll just show example to explain things. I use /usr/bin/sort as a reference how to sort, I do not plan to use it but it shows what other people decided before.

> * SCUMM
>   * ScummVM - very active development, C++. List of supported games is here (repository). 
> * 1945
>   * Py1945 - halted development, Python, GPL (repository). 
> * 3D Deathchase
>   * Deathchase 3D - C, GPL2 (repository). 

Scumm is obviously not in place, what about "3D Deathchase" vs "1945"? Should we consider numbers (3 < 1945) or letters (1 < 3)? (Hint: /usr/bin/sort has the -n command line argument)

>Alone in the Dark
>Alone in the Dark 2
>Jack in the Dark
>Alone in the Dark 3
> * Free in the Dark - development halted, C, GPL (repository). 

Should we sort the title by their name or by their release date?

>BurgerTime
>バーガータイム
>Hamburger
>ハンバーガー
> * BurgerSpace - halted development, C++, GPL2 (repository).

What about non-latin names? (Hint: /usr/bin/sort put them before latin names)

>Sensitive
> * One Way To Go - active development, Lua, GPL3 (repository).
>
>The Sentinel
> * sentinel - sporadic development, JavaFX, no specified licence (repository).
>
>Seven Kingdoms
> * Seven Kingdoms: Ancient Adversaries - active development, C++ (repository).

Any rules about "The" keyword?

>Wolfenstein 3D
>Spear of Destiny
> * ECWolf - active development, C++ (repository). 

Should we sort this and put "Spear of Destiny" first and put this with other games starting with "S" when everybody would probably search "Wolfenstein" instead?

**Comment by wonea** [comment]
Here's my two cents

>        SCUMM
>           ScummVM - very active development, C++. List of supported games is here (repository)
>      1945
>            Py1945 - halted development, Python, GPL (repository).
>        3D Deathchase
>            Deathchase 3D - C, GPL2 (repository).

We should definitely include numerics in the sort order. I'm not sure what to do about SCUMM.

Definitely consider non-latin named games.

> Wolfenstein
> Spear Of Destiny

I think games being grouped by their associated name(s) is fine. Otherwise we'd end with duplicate entries. The leading name (most known as) should be used for sort order. So the Ultima games would remain together.
