### ISSUE TITLE
Hunter

### ISSUE THREAD

**Issue by wonea** [piranha/osgameclones#178]
Possibility of a Hunter remake being made. Not sure whether it will be open source or related to;

http://sourceforge.net/projects/newhunter/

Remake currently in the works
http://eab.abime.net/showthread.php?t=76593&page=4

Original Game
http://en.wikipedia.org/wiki/Hunter_%28video_game%29#Reception

**Comment by wonea** [comment]
Worth noting the sourceforge project never got passed the planning stage, and there are no available files or source :-(

**Comment by nikuda** [comment]
Closing since no updates.
