### ISSUE TITLE
Zelda: Link to the Past

### ISSUE THREAD

**Issue by piranha** [piranha/osgameclones#179]
Got a mail:

first of all sorry for not creating an Issue on github. I do not have an account yet.
I saw you linked lttp for grapefruitjs. He has it deprecated and tries to port it over
to phaser ( https://github.com/photonstorm/phaser or http://phaser.io/ ):

https://github.com/englercj/lttp-phaser 

Maybe it could be added.

**Comment by wonea** [comment]
I've dropped the URL because I think that links to the old repository.
