### ISSUE TITLE
The Tower of Druaga

### ISSUE THREAD

**Issue by wonea** [piranha/osgameclones#189]
Wrote this stub then realised there's no source code. Can't find it, if anyone knows?

https://code.google.com/p/tower-of-druaga/

Empty repository!
![2015-06-03 14_07_51-tower-of-druaga - revision 1_ _trunk](https://cloud.githubusercontent.com/assets/557192/7960655/0d6e21aa-09fa-11e5-82cf-dd64a5d6070b.png)

Stub:
- name: The Tower of Druaga
  clones:
  - name: Tower of Druaga
    added: 2015-05-19
    url: https://code.google.com/p/tower-of-druaga/
    repo: http://tower-of-druaga.googlecode.com/svn/trunk/
    info: GPL3

**Comment by nikuda** [comment]
Closing since no trace of this game.
