### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by wonea** [piranha/osgameclones#195]
Website seems to be down. My distill web watcher caught this error;

![2015-06-12 15_24_36-alert_ open source game clones _ fastmail](https://cloud.githubusercontent.com/assets/557192/8132114/47159338-1117-11e5-9cc6-fed367ae410e.png)

**Comment by piranha** [comment]
My vhost on digital ocean has died and as a result all my sites were down. :( OSGC should be up now.
