### ISSUE TITLE
Dungeon Master Port and Clones

### ISSUE THREAD

**Issue by Ty-Guy5** [piranha/osgameclones#234]
Neat list we have here!

There's a C++ Port for the old Atari game, Dungeon Master, and its sequel, Chaos Strikes Back. It's called CSBwin, and it's code is (technically) open source. Following the links on the main page at http://dungeon-master.com/ will give you CBSwin (high fidelity to original) and a few other clones (RTC, Return to Chaos, is the big one). It's been modified to allow creation of custom dungeons, some of which are very fun! I even wrote a dungeon myself, several years back.

I would recommend linking to http://dungeon-master.com/ for an intro, links to the clones, and the community forums. 
Clicking "CSBwin" from there brings you to http://dmweb.free.fr/?q=node/851,  with the list of the downloadable (playable) files, including versions for Windows, Linux, Mac, and PocketPC. 
Also link to http://www.ragingmole.com/RTC/ for RTC.

**Comment by wonea** [comment]
Thanks for the heads up about this game. Always great to find clones for games we haven't listed here before!.
