### ISSUE TITLE
FOnline engine (Fallout 1/2)

### ISSUE THREAD

**Issue by Anthony-Gaudino** [piranha/osgameclones#255]
FOnline engine was created by a Russian group of Fallout fans, this engine can use assets from Fallout 1/2 and other games.

Many improvements were made in relation to the original Fallout 1/2 engine, including the use of 3D models and multiplayer.

This engine is used on many Fallout style community games, including multiplayer and single player games, but most of them didn't changed the engine core much. Most games are "clones" of Fallout Online and there's a "clone" of Fallout Van Buren, both games were never released by Interplay.

There are many different games using the engine:
* FOnline 2
* FOnline 2238
* FOnline Reloaded
* FOnline: Ashes of Phoenix
* Van Buren (http://www.moddb.com/games/f3-van-buren     single player)
* and many others...

There are many source code repositories of the engine, there's some on GitHub:
* Source of FOnline 2238 and tools - https://github.com/rotators
* https://github.com/alexknvl/fonline

**Comment by wonea** [comment]
Thanks for information, this is a really great find. Thank you!

**Comment by piranha** [comment]
Done in #261
