### ISSUE TITLE
PARPG - Fallout Inspired

### ISSUE THREAD

**Issue by DomtronVox** [piranha/osgameclones#256]
Fallout 1 and 2 __inspired__. No longer actively developed. Written in python using an FOSS C++ framework (FIFE www.fifengine.de). I believe the code license is GPL/BY-SA [forum discussion link](http://forums.parpg.net/index.php?topic=770.0)

Here is the web site link http://blog.parpg.net/

**Comment by piranha** [comment]
Done in #261
