### ISSUE TITLE
Site hijacked?

### ISSUE THREAD

**Issue by foobar13373** [piranha/osgameclones#282]
What happened to http://osgameclones.com/?

**Comment by piranha** [comment]
Wow! I'm sorry, it's not really hijacked, that's some misconfiguration with nginx and I still can't find what's going on - everything seems ok, except it doesn't direct queries to correct vhost.

**Comment by piranha** [comment]
Huh, found, it's [a new change in dokku](http://dokku.viewdocs.io/dokku/deployment/dockerfiles/#exposed-ports) - I wish they warned about this with very big letters somewhere.
