### ISSUE TITLE
liberatedgames.com is down for quite some time now

### ISSUE THREAD

**Issue by foobar13373** [piranha/osgameclones#283]
http://www.liberatedgames.com/ is linked in the introduction, but the site is down for quite some time now.

**Comment by piranha** [comment]
That's pretty sad. :( I wonder if it's possible to reach out to owner somehow and restore it... I'll try to find a way; if anybody else want to do that as well, that would be great.

**Comment by foobar13373** [comment]
It seems offline for 9 month or so:
https://www.changedetection.com/log/org/liberatedgames/index_log.html

The two domains liberatedgames.com and liberatedgames.org belong to the webhoster godaddy.com.

**Comment by piranha** [comment]
That's a sad story :( I wrote a mail to Marv without doing much research beforehand, but it seems it won't be replied...

**Comment by piranha** [comment]
Oh! I've got the reply actually! He says I can have the domains if I want them, but then what use I would have for them if there is no content...

**Comment by foobar13373** [comment]
Well, not asking him won't give any results _for sure_, so you can not lose anything by asking, only win or staying as before. ;)

**Comment by cxong** [comment]
Well looks like the domain is now occupied by a spam website. Nothing more to do.
