### ISSUE TITLE
Some indication of different types of content

### ISSUE THREAD

**Issue by piranha** [piranha/osgameclones#30]
It would be beneficial to mark in some nice way different types of games, i.e. direct descendants of code and clones, those who need original content and those who have free one available. Maybe something else?

Anyway, the question is - how to mark it. The best idea coming to my head is icons. But then should this icons look?

Plus - if all the games are marked in some way or another, it would be possible to add filtering using JS on site ("show me only games with free content").

**Comment by wonea** [comment]
@cxong I'd really like to see the icons. Any chance of a separate pull request just for the those? @Mailaender black and white icons would keep with the minimalistic approach

**Comment by cxong** [comment]
I'm a bit reluctant about adding icons now, I think we need a designer to undertake this task.

We already have clickable labels now, so the functionality is there. We also have colour-coded playable labels. Having icons must improve visibility, and make things look better. But:
- There are lots of different labels; having too many icons can make things look cluttered and less visible
- Not all icons look good in this small size
- Not all labels have appropriate icons, e.g. SDL is a popular framework but it doesn't have a recognisable icon

So unless the icons are well designed, we might not improve things over how they are right now.

**Comment by nikuda** [comment]
Suggest we close this issue since the main things have been achieved. The icons/design issue can be brought up in another issue when they arise again. @cxong @wonea

**Comment by nikuda** [comment]
Closing since the last bit that wasn't done is to be addressed in #533.
