### ISSUE TITLE
New game data keys: playable and recommended

### ISSUE THREAD

**Issue by nikuda** [piranha/osgameclones#336]
`playable:Boolean` = if the game can be played, currently 'playable' string is placed either in the development `status` keys or in the `info` key. 

`recommended:Boolean` = games of very high quality/playability, determines what gets rendered in the position that ScummVM occupies now.

**Comment by nikuda** [comment]
Ah already talked about in #30, agree with everything in this comment https://github.com/piranha/osgameclones/issues/30#issuecomment-40033883.

**Comment by wonea** [comment]
I'm not sure about recommended, but playable: would be a good start.

**Comment by piranha** [comment]
I'd say if we can come up with criteria for `recommended`, then it would be nice. If we can't, I would rather leave ScummVM in place just because it implements so many games and that's it.

`playable` sounds good!
