### ISSUE TITLE
Tetris clone

### ISSUE THREAD

**Issue by spypunk** [piranha/osgameclones#351]
- name: tetris
  clones:
    - name: tetris
      repo: https://github.com/spypunk/tetris
      info: java 8, WTFPL, playable, active
      added: 2016-08-19
      media:
        - url : https://a.fsdn.com/con/app/proj/spypunk-tetris/screenshots/s.png

**Comment by wonea** [comment]
Thanks

**Comment by spypunk** [comment]
I forgot the 'playable' and 'active' info tags.
