### ISSUE TITLE
REGoth - Gothic 1/2 engine reimplementation

### ISSUE THREAD

**Issue by szaromrok** [piranha/osgameclones#355]
- names: Gothic, Gothic II
  - clones:
    - name: REGoth
      url: https://github.com/degenerated1123/REGoth
      repo: https://github.com/degenerated1123/REGoth
      info: active development, playable, C++, GPLv3, requires original files
      media:
     - url: http://i65.tinypic.com/14mzzi8.jpg
       image: http://i66.tinypic.com/29lz91k.jpg

**Comment by wonea** [comment]
Thanks
