### ISSUE TITLE
OpenTESArena - The Elder Scrolls: Arena

### ISSUE THREAD

**Issue by afritz1** [piranha/osgameclones#357]
Hi. This is an open-source project for The Elder Scrolls: Arena. 

https://github.com/afritz1/OpenTESArena

The codebase is fairly young, but some of the interface is already working and you can walk around in the test world. It currently runs on Windows and Linux. I believe it can also be considered FOSS.

This project is unaffiliated with the existing links for Arena. Maybe consider deleting `opentesarena` since that link is broken. A user made a fork of WinArena at https://github.com/pralinor/opentesarenapp, and that repository has a bit more source code than the download available at UESP [here](http://www.uesp.net/wiki/Arena:Files#Misc_Utilities), though the last time it was updated was in 2009, so maybe consider either updating `opentesarenapp` to that GitHub link or delete it as well.

```
- name: The Elder Scrolls: Arena
  clones:
    - name: OpenTESArena
      repo: https://github.com/afritz1/OpenTESArena
      info: active development, not playable, C++/SDL2, MIT, requires original files
```

**Comment by wonea** [comment]
Thanks
