### ISSUE TITLE
Splitting games.yaml in many files

### ISSUE THREAD

**Issue by piranha** [piranha/osgameclones#363]
At almost 8 thousands lines it seems games.yaml became too big to be convenient. I think I'm just going to split it in a file per single game.

**Comment by nikuda** [comment]
Hmm 600+ game files might be annoying to deal with.

Maybe alphanumerical?

```
games/
  0-9.yaml
  a.yaml
  b.yaml
  ...
```

**Comment by piranha** [comment]
Actually, maybe. And just collect them in order, and skip name as an implementation detail. Sure, that could be nicer.

**Comment by tukkek** [comment]
Closing this since it seems to have been done a couple months ago.
