### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by nikuda** [piranha/osgameclones#377]
Not clear what license this repository falls under?

**Comment by piranha** [comment]
I'm not exactly sure what's the right one to choose. Content is not a code, is it ok to put a MIT license on everything? Or should it be some Creative Commons license?

Also, I wonder if there is anything to be worried about if I just put a license here without contacting previous contributors. Should I just assume they were contributing in a good will and are OK with licensing content however I want?

**Comment by nikuda** [comment]
It seems one of the Creative Commons licenses are most suitable for data/content.

* CC0 is closest to Unlicense/Public Domain
* CC-BY is closest to Apache/MIT/BSD, free use
* CC-BY-SA to GPL/MPL, only if you use the same license
* CC-BY-NC doesn't allow commercial use

This is useful: https://creativecommons.org/choose/

http://choosealicense.com/non-software/

**Comment by piranha** [comment]
I've added license, I guess double-licensing code under MIT and content under CC-BY makes the most sense.

I hope what I did is the right way, not sure what's the legal conditions about those contributions which were done before license was in - but hopefully nobody will object. :-)
