### ISSUE TITLE
Avast 6 antivirus won't let me open http://osgameclones.com/

### ISSUE THREAD

**Issue by Fixer-007** [piranha/osgameclones#384]
For some strange reason Avast 6 antivirus blocks me from viewing the site, it gives me this:
Trojan alert:
site: http://osgameclones.com/|>{gzip}
virus: JS:ScriptIP-inf [Trj]
process: firefox.exe

I've checked the site with VirusTotal and it gives no errors...
I was able to view the site via google translate. I'm using Firefox with noscript and adblock on Win7.

**Comment by piranha** [comment]
Wow, no idea how to fix that. It's certainly free of viruses, but something triggers avast...

**Comment by piranha** [comment]
I guess you can either whitelist the site or ask Avast support to check where their heuristic fails.

**Comment by OvermindDL1** [comment]
It is an Avast issue.  Avast has a lot of bugs related to similar checks.  If you report it to them they can fix it but otherwise just whitelist it yeah.
