### ISSUE TITLE
Genre for "Sid Meier's Pirates!"

### ISSUE THREAD

**Issue by tukkek** [piranha/osgameclones#412]
Regarding #411, @cxong has brought into question the actual genre for this game. Since neither of us had played it recently it stays an open question for those familiar with it. There also seems to be a matter of there being 2 versions of the game, maybe the latest one is a remake?

**Comment by piranha** [comment]
The one from 2004 is a remake of the original one from 1987. I'd say it's strategy. It had some adventure moments, but most of the time it's RTS.

**Comment by tukkek** [comment]
It's currently as action-adventure-RTS - the action mostly symbolizing there's some action sequences, depending on reaction time and such, it's not meant to suggest it's a shooter game or similar since that's another genre. I'm closing this for now if anyone has further issue or ideas just post a comment!
