### ISSUE TITLE
add xash3d

### ISSUE THREAD

**Issue by soredake** [piranha/osgameclones#425]
half-life 1 compatible game engine https://github.com/FWGS/xash3d

**Comment by piranha** [comment]
it's made from leaked sources and is not open source

**Comment by soredake** [comment]
>it's made from leaked sources
What? `Xash3D Engine is a custom Gold Source engine rewritten from scratch`
>and is not open source
`The library is licensed under GPLv3 license`

**Comment by cxong** [comment]
https://github.com/FWGS/xash3d/blob/master/engine/keydefs.h#L3

**Comment by nekonomicon** [comment]
@cxong, This file from Half-Life SDK and just modified keys.h from ID Tech 2
https://github.com/id-Software/Quake-2/blob/master/client/keys.h
