### ISSUE TITLE
FreeCol

### ISSUE THREAD

**Issue by psgoodman** [piranha/osgameclones#464]
[FreeCol](http://www.freecol.org/) is a clone of the Civilization spinoff Colonization, not sure if it should be its own entry or go under Civ.

**Comment by cxong** [comment]
Freecol is already in the list

**Comment by psgoodman** [comment]
My bad, was looking under C not S for Sid Meier.

**Comment by cxong** [comment]
yes it can be hard to find things on the site now that it's so big; the filters are a big help
