### ISSUE TITLE
Handling games which clone multiple games?

### ISSUE THREAD

**Issue by asiekierka** [piranha/osgameclones#479]
In particular, what would be the best way to handle Rocks'n'Diamonds? It aims to clone Boulder Dash, Emerald Mine, Sokoban and Supaplex in one large package.

**Comment by wonea** [comment]
There isn't an easy solution. ScummVM is marked compilation

**Comment by cxong** [comment]
This can be done now using the new schema; just fill in multiple names in the `remakes` or `clones` fields.
