### ISSUE TITLE
Your website should be served over HTTPS!

### ISSUE THREAD

**Issue by pgporada** [piranha/osgameclones#487]
Currently http://osgameclones.com is only available over an insecure HTTP connection. There is an https://osgameclones.com, but the certificate is long expired. Using a service such as [Let's Encrypt](https://letsencrypt.org), you can get free and automatically renewed HTTPS certificiates. To use Let's Encrypt, I typically recommend a client such as [Certbot](https://certbot.eff.org/) from the EFF or [Acme.sh](https://github.com/Neilpang/acme.sh). Once that's been configured, it would be beneficial to set up a webserver redirect rule to always redirect people to https://osgameclones.com.

Hope this helps!

**Comment by wonea** [comment]
HTTPS sounds like a good idea.

**Comment by nikuda** [comment]
Not worth the trouble right now. The content is entirely static.

**Comment by piranha** [comment]
It's not hard though, it's hosted in Dokku, so should be almost automatic. I'll try doing that. :)

**Comment by piranha** [comment]
Hey, how do you like that? :-) Also, http2 is enabled as well, site now is faster than ever. :)
