### ISSUE TITLE
CSS change for game status

### ISSUE THREAD

**Issue by wonea** [piranha/osgameclones#495]
status: # One of: playable, semi-playable, unplayable

Perhaps we should colour these;
payable - green
semi-playable - orange
unplayable - red

**Comment by JG916** [comment]
I can work on this. Just to be clear, would you like the playable/semi-playable/unplayable to be given their colors only on hover, or should they each be colored on both non-hover and hover?

**Comment by wonea** [comment]
I think they should be always coloured, it would be nice to scroll down the list and see the playable games.

**Comment by wonea** [comment]
Thank you very much, it looks great!
