### ISSUE TITLE
Add feed: to the game schema

### ISSUE THREAD

**Issue by wonea** [piranha/osgameclones#500]
Do you think we should add feed to the game schema? Eventually I would like to add a news page with a collated game updates.

What do you think @nikuda @cxong

**Comment by cxong** [comment]
ok; for the time being we can display the feed as an icon next to the name

**Comment by wonea** [comment]
@cxong sounds good!

**Comment by cxong** [comment]
![screen shot 2017-11-02 at 10 52 20 pm](https://user-images.githubusercontent.com/1083215/32324881-eb17443a-c020-11e7-8d02-c0dc87c03d2f.png)
