### ISSUE TITLE
Remove games which aren't actually free / open source

### ISSUE THREAD

**Issue by Wuzzy2** [piranha/osgameclones#521]
I noticed you include games under licenses like CC \<Whatever\>-**NC** or even CC \<Whatever\>-**ND**.

Sorry, those games are not actually free (i.e. neither “open source” nor “free software”).

According to the Open Source Definition (https://opensource.org/definition), if a license restricts usage of any kind, it can't be an open source license (point 1).

NC means Non-Commercial. Roughly spoken, it restricts commercial use (the actual meaning is a bit more complex but that's not the point right now). That's a direct violation of open source (see point 1) and therefore anything under CC-Whatever-NC should be removed.

ND means No Derivitaves and is a violation of point 3. These also don't belong to the list, obviously.

**Comment by wonea** [comment]
I'm okay with the broad licence support. I'd rather document all the available source codes, rather than be strict in our definition and the site be less comprehensive.

**Comment by Wuzzy2** [comment]
Well, you're just being dishonest with your website then. “open source” is a well-defined term, please don't redefine it.

I think the distinction between code and data in video games doesn't make sense. The data is just as an essential part of the game as the code. You can't just exclude the data and still call it a game.

Your list is technically not a list of open source games, but a list of open source game *engines*. That's an important difference.

It's a common misconception that “open source” only means that you can access the source code.

**Comment by nikuda** [comment]
> you're just being dishonest with your website 

You're free to make your own website and be more honest, instead of throwing random accusations around.

> I think the distinction between code and data in video games doesn't make sense.

This is counter to the fact that multiple game clones have their code open sourced and not their graphics set. The distinction is actually important and practical.

> The data is just as an essential part of the game as the code. You can't just exclude the data and still call it a game.

We're not the ones doing this, we don't actually have control over what's catalogued here if that's not clear to you.

**Comment by cxong** [comment]
Being actually free/open is important for some people, I think we can all agree. Nevertheless partially non-free games are also useful, for example, some may be interested in finding games with a free engine + nonfree assets, so they can work on a free asset replacement.

I'd welcome suggestions on how we can make the free/non-free distinction more clear, while keeping the website easy to use. Perhaps a custom filter to filter out those that aren't fully free? Or some links to good websites on why free is important?
