### ISSUE TITLE
Check AUR for open source clones

### ISSUE THREAD

**Issue by neuromancer** [piranha/osgameclones#91]
There are some (or maybe lots) of open source [clones](https://aur.archlinux.org/packages/?O=0&C=6&SeB=nd&K=clone&outdated=&SB=n&SO=a&PP=50&do_Search=Go) / [ports](https://aur.archlinux.org/packages/?O=0&C=6&SeB=nd&K=port&outdated=&SB=n&SO=a&PP=50&do_Search=Go) / [reimplementations](https://aur.archlinux.org/packages/?O=0&C=6&SeB=nd&K=reimplementation&outdated=&SB=n&SO=a&PP=50&do_Search=Go) in the AUR, e.g, this [one](https://aur.archlinux.org/packages/glfrontier/), waiting to be discovered!. 
I think we should start scanning that database..

**Comment by wonea** [comment]
I've gone through the Arch Linux and FreeBSD links and added all the links which are good. I'll vote to close this issue now.

**Comment by wonea** [comment]
For future reference and review I also found this page (a bit friendlier)

https://wiki.archlinux.org/index.php/List_of_games
